/**
 * @file console_record_model.h
 * @brief QML-facing console record model.
 */

#ifndef SERIAL_ASSISTANT_CONSOLE_RECORD_MODEL_H
#define SERIAL_ASSISTANT_CONSOLE_RECORD_MODEL_H

#include <QAbstractListModel>
#include <QByteArray>
#include <QDateTime>
#include <QString>
#include <QVector>

/**
 * One console row generated by receive, transmit, or system events.
 */
struct ConsoleRecord
{
    quint64 id = 0;
    QDateTime timestamp;
    QByteArray rawData;
    QString direction;
    QString text;
    QString hexText;
    bool isError = false;
};

/**
 * Stores bounded console records and exposes them to QML.
 */
class ConsoleRecordModel final : public QAbstractListModel
{
    Q_OBJECT

public:
    enum Role {
        IdRole = Qt::UserRole + 1,
        RecordTimeRole,
        DirectionRole,
        ContentRole,
        TextRole,
        HexTextRole,
        ByteCountRole,
        IsErrorRole,
        DirectionColorRole
    };
    Q_ENUM(Role)

    explicit ConsoleRecordModel(QObject* parent = nullptr);

    [[nodiscard]] int rowCount(const QModelIndex& parent = QModelIndex()) const override;
    [[nodiscard]] QVariant data(const QModelIndex& index, int role = Qt::DisplayRole) const override;
    [[nodiscard]] QHash<int, QByteArray> roleNames() const override;

    void appendReceive(const QDateTime& timestamp, const QByteArray& data, const QString& text, const QString& hexText);
    void appendTransmit(const QDateTime& timestamp, const QByteArray& data, const QString& text, const QString& hexText);
    void appendSystem(const QString& message, bool isError = false);

    Q_INVOKABLE void clear();

private:
    void appendRecord(ConsoleRecord record);
    void enforceLimit();

    QVector<ConsoleRecord> m_records;
    quint64 m_nextId = 1;
    int m_maxRecords = 5000;
};

#endif
